require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 400
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  Max: 50

# RSpec настройки
RSpec/ExampleLength:
  Max: 50
  Exclude:
    - 'spec/integration/**/*'

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
