require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'config/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 250
  Exclude:
    - 'spec/**/*'

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

Metrics/ClassLength:
  Max: 800
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 50
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 6

Style/IfUnlessModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

Style/StringChars:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true
  Exclude:
    - 'lib/yahtzee_bot/message_handler.rb'

RSpec/ExampleLength:
  Max: 100
  Exclude:
    - 'spec/integration/**/*'

RSpec/MultipleExpectations:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NestedGroups:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/FilePath:
  Exclude:
    - 'spec/unit/yahtzee_bot/message_handler_spec.rb'